// Reference file — copy to config.js and fill in your values
// config.js is auto-generated by: bash scripts/generate-config.sh
const firebaseConfig = {
  apiKey: "your-firebase-api-key",
  authDomain: "your-project.firebaseapp.com",
  projectId: "your-project-id",
  storageBucket: "your-project.appspot.com",
  messagingSenderId: "000000000000",
  appId: "1:000000000000:web:xxxxxxxxxxxxxx",
  measurementId: "G-XXXXXXXXXX",
};
export default firebaseConfig;
