FROM nginx:alpine AS production

RUN rm -rf /usr/share/nginx/html/*

COPY frontend/ /usr/share/nginx/html/
COPY infra/nginx/frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
