#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-.env}"

if [ -f "$ENV_FILE" ]; then
  set -a
  source "$ENV_FILE"
  set +a
fi

# Main dashboard config
cat > frontend/js/config.js <<EOF
// Auto-generated by generate-config.sh — do not edit
window.FIREBASE_CONFIG = {
  apiKey: "${FIREBASE_API_KEY:-}",
  authDomain: "${FIREBASE_AUTH_DOMAIN:-}",
  projectId: "${FIREBASE_PROJECT_ID:-}",
  storageBucket: "${FIREBASE_STORAGE_BUCKET:-}",
  messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID:-}",
  appId: "${FIREBASE_APP_ID:-}",
  measurementId: "${FIREBASE_MEASUREMENT_ID:-}",
};
EOF

# login-scripts config (ES module)
cat > login-scripts/config.js <<EOF
// Auto-generated by generate-config.sh — do not edit
const firebaseConfig = {
  apiKey: "${FIREBASE_API_KEY:-}",
  authDomain: "${FIREBASE_AUTH_DOMAIN:-}",
  projectId: "${FIREBASE_PROJECT_ID:-}",
  storageBucket: "${FIREBASE_STORAGE_BUCKET:-}",
  messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID:-}",
  appId: "${FIREBASE_APP_ID:-}",
  measurementId: "${FIREBASE_MEASUREMENT_ID:-}",
};
export default firebaseConfig;
EOF

echo "✓ Generated frontend/js/config.js"
echo "✓ Generated login-scripts/config.js"
